services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/dev-aurifi-frontend:latest
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - VITE_API_URL=${API_URL}
    restart: unless-stopped
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "service=frontend"

  backend:
    image: ${DOCKERHUB_USERNAME}/dev-aurifi-backend:latest
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DBNAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - OPENAI_ASSISTANT_ID=${OPENAI_ASSISTANT_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./datasets:/app/datasets  # Add this line to persist datasets
    restart: unless-stopped
    networks:
      - app-network
    labels:
      - "traefik.enable=true" 
      - "service=backend"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - app-network
    labels:
      - "service=nginx"

networks:
  app-network:
    driver: bridge
